"""create missing_info_reports table

Revision ID: 0b2f41134e30
Revises: 0001
Create Date: 2026-06-20 18:00:41.469214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2f41134e30'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missing_info_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name='fk_missing_info_agent_id'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name='fk_missing_info_chat_id'),
    sa.PrimaryKeyConstraint('id', name='pk_missing_info_reports'),
    sa.UniqueConstraint('uuid', name='uq_missing_info_reports_uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missing_info_reports')
    # ### end Alembic commands ###
